# This is a workflow to pull weather data from NOMADS and process them with am using µcast

name: µcast

# Controls when the action will run.
on:
  # Schedule the workflow
  schedule:
    - cron: '15 5/6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Create new forecast tables and stage them as artifacts
  mktab:
    runs-on: ubuntu-latest
    container: astcon/ucast:latest
    strategy:
      matrix:
        site: ['ALMA', 'APEX', 'GLT', 'JCMT', 'KP', 'LMT', 'PDB', 'PV', 'SMA', 'SMT', 'SPT']

    steps:
      - name: Checkout database
        uses: actions/checkout@v2

      - name: Make new forecast table
        run: |
          . /usr/local/am/bin/am.sh
          ucast mktab ${{ matrix.site }} --no-link

      - name: Remove old tables
        run: |
          rm -f $(ls ${{ matrix.site }} | head -n -9)

      - name: Upload tables as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.site }}
          path: ${{ matrix.site }}
